# Generated by Django 4.2.2 on 2023-06-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок')),
                ('description_short', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('description_long', models.TextField(blank=True, verbose_name='Описание')),
                ('coordinate_lng', models.FloatField(null=True, verbose_name='Долгота')),
                ('coordinate_lat', models.FloatField(null=True, verbose_name='Широта')),
            ],
        ),
    ]
